### ISSUE TITLE
[Epic] 모달 - 글 조회

### ISSUE THREAD

**Issue by chlangus** [PROJECT-BLOB/front-end#10]
### 에픽 내용
- [ ] 글 조회(작성위치 및 카테고리 ...)
- [ ] 사용자 별 좋아요, 북마크  처리
- [ ] 사용자 별 토글 메뉴 항목 처리(글 삭제 및 신고)

### 예상 기간
- 2일

### 관련 사항
-
