### ISSUE TITLE
[Epic] Refactoring / Bug-fix Issues

### ISSUE THREAD

**Issue by Dev-Duke-Seo** [PROJECT-BLOB/front-end#154]
### 에픽 내용

- [ ] 반응형 디자인 점검 : 각자 맡은 부분 위주로 진행해주세요.
- [ ] 글쓰기 모달: 도시검색/미니맵 다른 상태값이 적용됨
- [ ] 미니맵 마커 변경
- [ ] 현위치 변경
- [ ] 아이콘 변경
- [ ] 바텀시트 수정
  - [ ] 모바일에 windows가 없어 작동안함.
- [ ]  마커 / 카테고리 → 색상 통일
- [ ] 글씨 크기 확인
- [ ] 글쓰기 카테고리 선택 이중
- [ ] 리프레시 토큰 만료시 자동 로그아웃 처리
- [ ] production/dev env 이원화 → 퍼블릭 url에서도 서비스 가능하게 만들기.
- [ ] 실제 서비스 하려면 → 약관동의 페이지?
- [ ] 말풍선이 항상 가장 위에오게.

### 예상 기간
- 2주일

### 관련 사항
- 자기가 작업한 도메인에 구애 받지 말고 작업해주세요~!
- 단, 해당 작업자의 코드를 수정할땐 해당 코드의 작업자를 리뷰어로 선정해주시고 해당 팀원은 가급적 리뷰 부탁드립니다.
