### ISSUE TITLE
[Epic] 회원가입 페이지

### ISSUE THREAD

**Issue by haeyong9701** [PROJECT-BLOB/front-end#2]
### 에픽 내용
- [x] 회원가입 페이지 퍼블리싱
- [x] 회원이 회원가입 페이지에 들어온다.
- [x] 구글 회원가입 버튼을 클릭한다
- [x] 카카오 회원가입 버튼을 클릭한다
- [ ] 구글 회원가입: 실패
- [ ] 카카오 회원가입: 실패

### 예상 기간
- 2일

### 관련 사항
-
